version: "3.9"

services:
  web-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: on-failure
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"

  mariadb-server:
    image: mariadb:latest
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: admin135
      MYSQL_DATABASE: library
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: on-failure
    environment:
      PMA_HOST: mariadb-server
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: admin135
    ports:
      - "5000:80"

volumes:
  mariadb-data: